# Generated by Django 2.2.1 on 2019-06-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sku', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
